---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: php-project
  name: php-project
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: php-project
    spec:
      containers:
      - image: saikrishna01/php-project:latest
        name: php-project
        ports:
        - name: php-project
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: php-project
  name: php-project
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: php-project
